from models.model import EvidenceHierarchicalDamageModel


def build_model(config: dict) -> EvidenceHierarchicalDamageModel:
    model_cfg = config["model"]
    return EvidenceHierarchicalDamageModel(
        backbone_name=str(model_cfg["backbone"]),
        pretrained=bool(model_cfg["pretrained"]),
        input_mode=str(model_cfg["input_mode"]),
        feature_dim=int(model_cfg["feature_dim"]),
        token_dim=int(model_cfg["token_dim"]),
        evidence_dim=int(model_cfg["evidence_dim"]),
        dropout=float(model_cfg["dropout"]),
        use_tight_branch=bool(model_cfg["use_tight_branch"]),
        use_context_branch=bool(model_cfg["use_context_branch"]),
        use_neighborhood_branch=bool(model_cfg["use_neighborhood_branch"]),
        enable_alignment=bool(model_cfg.get("enable_alignment", True)),
        enable_prepost_fusion=bool(model_cfg.get("enable_prepost_fusion", True)),
        fusion_mode=str(model_cfg.get("fusion_mode", "diff_prod_concat")),
        enable_damage_aware_block=bool(model_cfg.get("enable_damage_aware_block", True)),
        enable_change_gate=bool(model_cfg.get("enable_change_gate", True)),
        use_cross_scale_attention=bool(model_cfg["use_cross_scale_attention"]),
        cross_scale_fusion_mode=str(model_cfg.get("cross_scale_fusion_mode", "tight_query_all_kv")),
        use_evidence_head=bool(model_cfg["use_evidence_head"]),
        use_hierarchical_head=bool(model_cfg["use_hierarchical_head"]),
        use_global_corn_aux=bool(model_cfg["use_global_corn_aux"]),
        enable_minor_boundary_aux=bool(model_cfg.get("enable_minor_boundary_aux", False)),
        head_type=str(model_cfg.get("head_type", "two_stage_hierarchical" if bool(model_cfg["use_hierarchical_head"]) else "flat_corn")),
        tight_token_count=int(model_cfg["tight_token_count"]),
        context_token_count=int(model_cfg["context_token_count"]),
        neighborhood_token_count=int(model_cfg["neighborhood_token_count"]),
        local_attention_heads=int(model_cfg["local_attention_heads"]),
        local_attention_layers=int(model_cfg["local_attention_layers"]),
        local_attention_layers_tight=None if model_cfg.get("local_attention_layers_tight") is None else int(model_cfg["local_attention_layers_tight"]),
        local_attention_layers_context=None if model_cfg.get("local_attention_layers_context") is None else int(model_cfg["local_attention_layers_context"]),
        local_attention_layers_neighborhood=None if model_cfg.get("local_attention_layers_neighborhood") is None else int(model_cfg["local_attention_layers_neighborhood"]),
        tight_window_size=int(model_cfg["tight_window_size"]),
        context_window_size=int(model_cfg["context_window_size"]),
        neighborhood_window_size=int(model_cfg["neighborhood_window_size"]),
        cross_scale_heads=int(model_cfg["cross_scale_heads"]),
        cross_scale_layers=int(model_cfg["cross_scale_layers"]),
        cross_scale_dropout=float(model_cfg["cross_scale_dropout"]),
        context_dropout_prob=float(model_cfg["context_dropout_prob"]),
        neighborhood_dropout_prob=float(model_cfg["neighborhood_dropout_prob"]),
        evidence_topk_ratio=float(model_cfg["evidence_topk_ratio"]),
        evidence_threshold=float(model_cfg["evidence_threshold"]),
        damage_decision_threshold=float(model_cfg.get("damage_decision_threshold", 0.5)),
        evidence_fusion_mode=str(model_cfg.get("evidence_fusion_mode", "concat_mlp_original")),
        evidence_gate_init_logit=float(model_cfg.get("evidence_gate_init_logit", -4.0)),
        enable_feature_calibration=bool(model_cfg.get("enable_feature_calibration", True)),
        evidence_scales=list(model_cfg.get("evidence_scales", ["tight", "context", "neighborhood"])),
        use_structural_two_stage_head=bool(model_cfg.get("use_structural_two_stage_head", False)),
        structural_two_stage_hidden_dim=int(model_cfg.get("structural_two_stage_hidden_dim", model_cfg.get("feature_dim", 768))),
        structural_two_stage_dropout=float(model_cfg.get("structural_two_stage_dropout", model_cfg.get("dropout", 0.1))),
        structural_two_stage_use_for_prediction=bool(model_cfg.get("structural_two_stage_use_for_prediction", False)),
        structural_two_stage_prob_mix_weight=float(model_cfg.get("structural_two_stage_prob_mix_weight", 0.0)),
        use_severity_aware_scale_router=bool(model_cfg.get("use_severity_aware_scale_router", False)),
        scale_router_hidden_dim=int(model_cfg.get("scale_router_hidden_dim", 512)),
        scale_router_dropout=float(model_cfg.get("scale_router_dropout", model_cfg.get("dropout", 0.1))),
        scale_router_use_for_prediction=bool(model_cfg.get("scale_router_use_for_prediction", False)),
        scale_router_prob_mix_weight=float(model_cfg.get("scale_router_prob_mix_weight", 0.0)),
        scale_router_init_gates=list(model_cfg.get("scale_router_init_gates", [0.5, 0.7, 0.3, 0.25])),
    )


__all__ = ["EvidenceHierarchicalDamageModel", "build_model"]
